apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 272468461328.dkr.ecr.ap-southeast-1.amazonaws.com/cc-frontend:latest
          imagePullPolicy: Always
          env:
            - name: USER_SVC_ADDR
              value: 'http://user-svc:8000'
            - name: MATCHING_SVC_ADDR
              value: 'http://matching-svc:8001'
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
